name: Deploy static content to Pages

on:
  push:
    branches: ["my-main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - run: |
          mkdir _build
          echo "<h1>Hello World!</h1>" > ./_build/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './_build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      
      - name: test
        run: |
          gpg -K

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v1.20.0
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# https://github.com/mollie/tf-provider-registry-api-generator/releases/download/v0.3.2/tf-provider-registry-api-generator_0.3.2_Linux_x86_64.tar.gz
